language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y unrar
  - sudo apt-get install -y p7zip-full
  - pear install pear/Archive_Tar
  - pecl install zip
  - phpenv rehash
  - composer install --prefer-source