language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip
  - sudo apt-get install -y unrar
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -y p7zip-rar
  - sudo apt-get install -y cabextract
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install zip; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install rar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then echo "phar.readonly = 0" > travis.hhvm.ini; fi;'

  - composer install --prefer-source

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then phpunit --verbose; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then cat travis.hhvm.ini; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini -i; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini $HOME/.phpenv/versions/hhvm/bin/phpunit; fi;'