language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip
  - sudo apt-get install -y unrar
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -y p7zip-rar
  - sudo apt-get install -y cabextract
  - pecl install zip
  - pecl install rar
  - phpenv rehash
  - composer install --prefer-source

script:
  - phpunit --verbose