language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip
  - sudo apt-get install -y unrar
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -y p7zip-rar
  - sudo apt-get install -y cabextract
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install zip; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install rar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then echo "phar.readonly = 0" > travis.hhvm.ini; fi;'
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
  - composer install --prefer-source

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --verbose; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then hhvm -c travis.hhvm.ini ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi;'
