language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y unzip
  - sudo apt-get install -y unrar
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -y p7zip-rar
  - sudo apt-get install -y cabextract
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install zip; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install rar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then phpenv rehash; fi;'

  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then echo "phar.readonly = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/hhvm.ini; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then phpenv config-add hhvm.ini; fi;'

  - composer install --prefer-source

script:
  - phpunit --verbose